name: Build and Check
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install Nix â„ï¸
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm
            trusted-users = runner root
            allowed-users = *

      - name: Link Cachix ğŸ”Œ
        uses: cachix/cachix-action@v10
        with:
          name: cosmos
          authToken: '${{ secrets.COSMOS_CACHE_KEY }}'

      - name: Check ğŸ”
        run: |
          ls -ld /dev/kvm
          whoami
          nix flake check

      - name: Run Shell ğŸš
        run: |
          whoami
          nix develop
